FROM ubuntu:trusty

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=curvehash/curvehash
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY curvehash.tar.gz /curvehash.tar.gz
RUN tar -xvf /curvehash.tar.gz

#xenial
#Missing requirement: libtool
#RUN apt install -yqq libtool-bin
RUN cd /curvehash/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /curvehash && scripts/windows-crosscompile/compile-curvehash.sh
